// Copy the release asciicut_core.wasm produced by `cargo build --release
// --target wasm32-unknown-unknown` into web/src/wasm/ so Vite can import it.
//
// The artifact is a *build product* (gitignored under web/src/wasm/*.wasm); it
// is regenerated by `npm run build:wasm` (which runs the cargo build first, see
// package.json). Kept in Node — not a shell cp — so the copy is portable across
// dev OSes and CI without a POSIX assumption (D6).
import { copyFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..");
const src = resolve(
  repoRoot,
  "target/wasm32-unknown-unknown/release/asciicut_core.wasm",
);
const destDir = resolve(here, "..", "src", "wasm");
const dest = resolve(destDir, "asciicut_core.wasm");

mkdirSync(destDir, { recursive: true });
copyFileSync(src, dest);
console.log(`copied ${src} -> ${dest}`);
